---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Inspect
no_index:
  directory:
    - t
    - inc
requires:
  HTTP::Request: '0'
  HTTP::Response: '0'
  Net::Pcap: '0'
  Scalar::Util: '0'
resources:
  repository: https://github.com/noxxi/p5-net-inspect
version: '0.309'
